name: Test unit tests CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  
jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: setup Msbuild
      uses: microsoft/setup-msbuild@v1.3.1

   #Run Server
    - name: Start CoreServer.exe in the background and run the FluidTransferTests
      run: |
         ./Debug/CoreServer.exe -c -s &
         sleep 2
         netstat -ntp
